import pymeshlab
file1 = open('pythonArgs.txt', 'r')
arguments = file1.readlines()
path = arguments[0].replace("\n", "")
minZ = arguments[1].replace("\n", "")
maxZ = arguments[2].replace("\n", "")
side = arguments[3]
ms = pymeshlab.MeshSet()
ms.load_new_mesh(path + side +'_head_moved.stl')
headID = ms.current_mesh_id()
ms.load_new_mesh(path + side + '_prox.stl')
proxID = ms.current_mesh_id()
ms.mesh_boolean_union(first_mesh=headID, second_mesh=proxID)
print(ms.number_meshes())
unionID = ms.current_mesh_id()
ms.conditional_face_selection(condselect='(z0 > ' + str(minZ) + ' && z0 < ' + str(maxZ) + ')')
print("selected faces=" + str(ms.current_mesh().selected_face_number()))

ms.laplacian_smooth(stepsmoothnum=25, boundary=False, cotangentweight=False, selected=True)

ms.mesh_boolean_intersection(first_mesh=headID, second_mesh=unionID)
ms.save_current_mesh(path + side + '_head_smoothed.stl')
ms.mesh_boolean_intersection(first_mesh=proxID, second_mesh=unionID)
proxID = ms.current_mesh_id()
ms.mesh_boolean_symmetric_difference_xor(first_mesh=headID, second_mesh=proxID)
xor = ms.current_mesh_id()
ms.mesh_boolean_difference(first_mesh=xor, second_mesh=headID)
ms.remove_isolated_pieces_wrt_diameter(mincomponentdiag=pymeshlab.AbsoluteValue(6))
ms.save_current_mesh(path + side + '_prox_smoothed.stl')
print(ms.number_meshes())
print('finished')